# Generated by Django 2.2.6 on 2019-12-19 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('b_time', models.DateTimeField(default=datetime.datetime(2019, 12, 19, 15, 57, 58, 393093), verbose_name='保存日期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
